Updated msp_merge_ancestors to match Python implementation
tskit-dev/msprime pull request #1782
Opened 2021-07-22 02:57 UTC by nikbaya

2021-07-22 09:00 UTC, jeromekelleher requested changes
Looks good, but there's a logic issue.

2021-07-22 09:00 UTC, jeromekelleher commented on lib/msprime.c
> +            new_node_id = (tsk_id_t) msp_get_num_nodes(self) - 1;
This needs to be *inside* the if statement, otherwise we overwrite the supplied new node id value.

2021-07-24 09:13 UTC, jeromekelleher commented
Yep, that's it! Now, we just need to [squash](https://stdpopsim.readthedocs.io/en/latest/development.html#rebasing) the commits into done, and we're good to merge.

2021-07-29 12:41 UTC, nikbaya commented
@jeromekelleher I think I squashed the commits, is there more to do before completing the PR?

2021-07-29 12:52 UTC, jeromekelleher approved these changes
All done, thanks @nikbaya!

2021-07-29 12:59 UTC, merged